// Generated by CoffeeScript 1.6.3
var Compiler, Parser, coffee2thrift, fs;

require('mocha');

require('chai');

fs = require('fs');

Parser = require('../lib/parser');

Compiler = require('../lib/compiler');

coffee2thrift = require('..');

describe('Parser', function() {
  it('parse', function() {
    var parser;
    parser = new Parser('superwolf');
    return parser.parse();
  });
  it('parse', function() {
    var code, parser;
    console.log(__dirname);
    console.log(__dirname + '/test.coffeethrift');
    code = fs.readFileSync(__dirname + '/test.coffeethrift', 'utf-8');
    console.log(code);
    parser = new Parser(code);
    return parser.parse();
  });
  it('parse + compile', function() {
    var code, compiler, parser;
    code = fs.readFileSync(__dirname + '/test.coffeethrift', 'utf-8');
    parser = new Parser(code);
    parser.parse();
    compiler = new Compiler(parser.nodes);
    return compiler.compile();
  });
  return it('package test', function() {
    var code;
    code = fs.readFileSync(__dirname + '/test.coffeethrift', 'utf-8');
    return console.log(coffee2thrift.parse(code));
  });
});
